### ISSUE TITLE
Slide Loss implement

### ISSUE THREAD

**Issue by dosemeion** [Krasjet-Yu/YOLO-FaceV2#17]
https://github.com/Krasjet-Yu/YOLO-FaceV2/blob/29bab8b31507c39ac61665a77334103215604d99/utils/loss.py#L30

a2 = math.exp(1 - auto_iou)？

**Comment by Krasjet-Yu** [comment]
Thanks for your issue!
Since auto_IOU was previously set to 0.5, this line of code has not changed. This bug has now been fixed.
