### ISSUE TITLE
训练时间

### ISSUE THREAD

**Issue by 15681160190** [Krasjet-Yu/YOLO-FaceV2#28]
作者您好，使用你的NWD和IOU结合的损失函数后，训练时间增加了三倍，是正常的吗

**Comment by Krasjet-Yu** [comment]
不正常，NWD基本不耗时。最后结果正常吗？

**Comment by 15681160190** [comment]
我是在yolov7上面测试的，结果也不正常，检查了一下应用方法应该没问题，不知道哪里出了问题
