### ISSUE TITLE
训练问题

### ISSUE THREAD

**Issue by shituo123456** [Krasjet-Yu/YOLO-FaceV2#8]
![image](https://user-images.githubusercontent.com/64970397/184296123-e76a271f-4889-47ee-9140-2deb2e41a066.png)

yolov5s原模型训练一轮map05都达到0.569.

![image](https://user-images.githubusercontent.com/64970397/184296192-e98168d8-b3f5-470f-bbc3-9fcac36670fb.png)
用yolo-facev2训练10轮还不到0.4.
请问：是有什么训练方法吗？

**Comment by dosemeion** [comment]
请问你有复现出作者的精度吗？
